#!/bin/bash
if [ $# -ne 2 ]; then
	echo "Provide a groupId and an artifactId in the parameters"
else
	mvn archetype:generate -DgroupId=$1 -DartifactId=$2 -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
fi
