#!/bin/bash
if [ $# -ne 1 ]; then
	echo "Provide a valid project name"
else
	django-admin startproject --template=https://github.com/SLOBYYYY/django-layout/zipball/master --extension=py,rst,gitignore,example $1
fi
